# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PortableClasses' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PortableClasses
  pod 'Firebase/Core'
  pod 'FirebaseUI'  
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

  target 'PortableClassesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PortableClassesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
